import os
import json

CANDIDATES_DIR = r"C:\Users\Ilia V\Documents\antigravity\calm-noether\Strata\bench\tournament2\candidates"
os.makedirs(CANDIDATES_DIR, exist_ok=True)

base_paths = {
    "pack": r"C:\Users\Ilia V\Documents\antigravity\calm-noether\Strata-data\packs\coder-iq1_m",
    "native": r"C:\Users\Ilia V\Documents\antigravity\calm-noether\Strata-data\models\coder-IQ1_M\Qwen3.8-Flash-Next-GSQ-RCO-IQ1_M-00001-of-00002.gguf",
    "ple_gguf": r"C:\Users\Ilia V\Documents\antigravity\calm-noether\Strata-data\models\coder-IQ1_M\Qwen3.8-Flash-Next-GSQ-RCO-IQ1_M-00002-of-00002.gguf",
    "profile": r"C:\Users\Ilia V\Documents\antigravity\calm-noether\Strata\data\expert-profile-coder.bin",
    "mtp": r"C:\Users\Ilia V\Documents\antigravity\calm-noether\Strata-data\mtp\rt"
}

candidates = [
    {
        "id": "S01",
        "name": "VRAM-Liberation",
        "category": "VRAM Budget & MTP Pruning",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "360",
            "--vram-reserve-mib", "450",
            "--expert-cache-cpu-order",
            "--kv-resident", "20480",
            "--prefill", "1024",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "2048",
            "--max-context", "65536",
            "--kv", "q4_0",
            "--pcie-frac", "0",
            "--short-read", "2048",
            "--adapt-every", "0",
            "--adapt-swaps", "0"
        ]
    },
    {
        "id": "S02",
        "name": "KV-Streaming",
        "category": "KV Streaming & Expert Scaling",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "380",
            "--vram-reserve-mib", "450",
            "--kv-resident", "20480",
            "--expert-cache-cpu-order",
            "--prefill", "1024",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "4096",
            "--max-context", "65536",
            "--kv", "q4_0",
            "--pcie-frac", "0",
            "--short-read", "2048",
            "--adapt-every", "0",
            "--adapt-swaps", "0"
        ]
    },
    {
        "id": "S03",
        "name": "Context-Crusher",
        "category": "Context Optimization & 32K Geometry",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "410",
            "--vram-reserve-mib", "450",
            "--expert-cache-cpu-order",
            "--prefill", "1024",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "4096",
            "--max-context", "32768",
            "--kv", "q4_0",
            "--pcie-frac", "0",
            "--short-read", "2048",
            "--adapt-every", "0",
            "--adapt-swaps", "0"
        ]
    },
    {
        "id": "S04",
        "name": "Expert-Profile-Master",
        "category": "Dynamic DMA Cache Adaptation",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "220",
            "--vram-reserve-mib", "480",
            "--expert-cache-cpu-order",
            "--adapt-every", "16",
            "--adapt-swaps", "4",
            "--prefill", "1024",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "4096",
            "--max-context", "65536",
            "--kv", "q4_0",
            "--pcie-frac", "0",
            "--short-read", "2048"
        ]
    },
    {
        "id": "S05",
        "name": "Huge-Pages-Engineer",
        "category": "Memory Subsystem & Page Locking",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "240",
            "--vram-reserve-mib", "440",
            "--expert-cache-cpu-order",
            "--adapt-every", "0",
            "--adapt-swaps", "0",
            "--prefill", "1024",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "4096",
            "--max-context", "65536",
            "--kv", "q4_0",
            "--pcie-frac", "0",
            "--short-read", "2048"
        ]
    },
    {
        "id": "S06",
        "name": "SSD-Direct-Oracle",
        "category": "Unbuffered IOCP Storage Architecture",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--ple-io", "direct",
            "--ple-row-cache", "1048576",
            "--ple-inflight", "64",
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "220",
            "--vram-reserve-mib", "480",
            "--expert-cache-cpu-order",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--kv", "q4_0",
            "--pcie-frac", "0",
            "--short-read", "2048",
            "--prefill", "1024",
            "--max-context", "65536",
            "--mtp-window", "4096",
            "--mtp", base_paths["mtp"]
        ]
    },
    {
        "id": "S07",
        "name": "MTP-Kill-MaxVRAM",
        "category": "MTP-MicroStub & Massive Expert VRAM Allocation",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "520",
            "--vram-reserve-mib", "260",
            "--expert-cache-cpu-order",
            "--adapt-every", "0",
            "--adapt-swaps", "0",
            "--prefill", "1024",
            "--spec", "2",
            "--spec-min-p", "0.90",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "512",
            "--max-context", "65536",
            "--kv", "q4_0",
            "--pcie-frac", "0",
            "--short-read", "2048"
        ]
    },
    {
        "id": "S10",
        "name": "PCIe-Frac-Scientist",
        "category": "PCIe Bus Micro-Offload",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "220",
            "--vram-reserve-mib", "480",
            "--expert-cache-cpu-order",
            "--adapt-every", "0",
            "--adapt-swaps", "0",
            "--prefill", "1024",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "4096",
            "--max-context", "65536",
            "--kv", "q4_0",
            "--pcie-frac", "0.10",
            "--short-read", "2048"
        ]
    },
    {
        "id": "S12",
        "name": "StrataGP-Hunter",
        "category": "Thread Spin & Memory Locking",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "230",
            "--vram-reserve-mib", "460",
            "--expert-cache-cpu-order",
            "--adapt-every", "0",
            "--adapt-swaps", "0",
            "--prefill", "1024",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "4096",
            "--max-context", "65536",
            "--kv", "q4_0",
            "--pcie-frac", "0",
            "--short-read", "2048"
        ]
    },
    {
        "id": "S13",
        "name": "Reddit-Scout-Fresh",
        "category": "KV-Resident & Zen 2 Pool Alignment",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "380",
            "--vram-reserve-mib", "460",
            "--expert-cache-cpu-order",
            "--adapt-every", "0",
            "--adapt-swaps", "0",
            "--prefill", "1024",
            "--spec", "3",
            "--spec-min-p", "0.84",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "4096",
            "--max-context", "65536",
            "--kv", "q4_0",
            "--kv-resident", "20480",
            "--pool-workers", "5",
            "--pcie-frac", "0",
            "--short-read", "2048"
        ]
    },
    {
        "id": "S15",
        "name": "PLE-IO-Optimizer",
        "category": "Deep IOCP & Expanded PLE Row Cache",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--ple-io", "direct",
            "--ple-row-cache", "2097152",
            "--ple-inflight", "128",
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "220",
            "--expert-cache-cpu-order",
            "--vram-reserve-mib", "480",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--prefill", "1024",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "4096",
            "--max-context", "65536",
            "--kv", "q4_0",
            "--pcie-frac", "0",
            "--short-read", "2048",
            "--adapt-every", "0",
            "--adapt-swaps", "0"
        ]
    },
    {
        "id": "S16",
        "name": "Attention-Geometry",
        "category": "32K INT8 Precision Inversion",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "260",
            "--vram-reserve-mib", "480",
            "--expert-cache-cpu-order",
            "--adapt-every", "0",
            "--adapt-swaps", "0",
            "--prefill", "1024",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "4096",
            "--max-context", "32768",
            "--kv", "int8",
            "--pcie-frac", "0",
            "--short-read", "2048"
        ]
    },
    {
        "id": "S18",
        "name": "Native-Shard-Pioneer",
        "category": "Warp-Sum Native Reduction & Unpinned Order",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "230",
            "--vram-reserve-mib", "460",
            "--adapt-every", "0",
            "--adapt-swaps", "0",
            "--prefill", "1024",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "4096",
            "--max-context", "65536",
            "--kv", "q4_0",
            "--pcie-frac", "0",
            "--short-read", "2048"
        ]
    },
    {
        "id": "S20",
        "name": "Cross-Engine-Analyst",
        "category": "Cross-Engine Architectural Transfer",
        "args": [
            "--pack", base_paths["pack"],
            "--native", base_paths["native"],
            "--ple-gguf", base_paths["ple_gguf"],
            "--expert-profile", base_paths["profile"],
            "--expert-cache", "240",
            "--expert-cache-per-layer",
            "--vram-reserve-mib", "450",
            "--expert-cache-cpu-order",
            "--adapt-every", "0",
            "--adapt-swaps", "0",
            "--prefill", "1024",
            "--spec", "3",
            "--spec-min-p", "0.82",
            "--suffix-draft", "3",
            "--prompt-cache", "16",
            "--prompt-cache-root", "16",
            "--prompt-cache-every", "128",
            "--mtp", base_paths["mtp"],
            "--mtp-window", "4096",
            "--max-context", "65536",
            "--kv", "q4_0",
            "--pcie-frac", "0",
            "--short-read", "2048"
        ]
    }
]

for c in candidates:
    fname = os.path.join(CANDIDATES_DIR, f"{c['id']}_candidate.json")
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(c, f, indent=2)
    print(f"Written: {fname}")
